name: RUN ECR

on:
  push:
    branches:
      - cbt

jobs:
  Check_Lint_Test_First:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci

    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        tsc: true

    - name: Run Test & Coverage Report #Coverage는 테스트가 어느 부분을 커버하고 있는지를 나타내는 지표
      run: npm run test:cov

      
  Second_Run_Ecr:
      runs-on: ubuntu-latest

      steps: 
      - name: Checkout code
        uses: actions/checkout@v3
