name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # 빌드 단계 (옵션)
    - name: Build
      run: |
        npm install
        npm run build
    # EC2 서버에 배포
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 3.39.216.163
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE }}
        script: |
          cd /home/ubuntu/cicd
          git pull origin main
          docker-compose -f docker-compose.prod.yml up -d