name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main

jobs:
  test: # 이름 변경
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci

    - name: Install Linters
      run: |
        npm install eslint --save-dev
        npm install prettier --save-dev
        
    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        eslint_args: "{src,apps,libs,test}/**/*.ts"
        prettier: true
    
    - name: Run Test
      run: npm test
