name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm' # You can specify your desired Node.js version here
      - run: npm install
      - run: npm test